/** Dicionário EN (pipeline) → PT-BR (interface). */
export const TRADUCAO_SELECOES: Record<string, string> = {
  MEXICO: "México",
  "SOUTH AFRICA": "África do Sul",
  "SOUTH KOREA": "Coreia do Sul",
  CZECHIA: "República Tcheca",
  CANADA: "Canadá",
  "BOSNIA AND HERZEGOVINA": "Bósnia e Herzegovina",
  QATAR: "Catar",
  SWITZERLAND: "Suíça",
  BRAZIL: "Brasil",
  MOROCCO: "Marrocos",
  HAITI: "Haiti",
  SCOTLAND: "Escócia",
  "UNITED STATES": "Estados Unidos",
  PARAGUAY: "Paraguai",
  AUSTRALIA: "Austrália",
  TURKIYE: "Turquia",
  GERMANY: "Alemanha",
  CURACAO: "Curaçao",
  "IVORY COAST": "Costa do Marfim",
  ECUADOR: "Equador",
  NETHERLANDS: "Holanda",
  JAPAN: "Japão",
  SWEDEN: "Suécia",
  TUNISIA: "Tunísia",
  BELGIUM: "Bélgica",
  EGYPT: "Egito",
  IRAN: "Irã",
  "NEW ZEALAND": "Nova Zelândia",
  SPAIN: "Espanha",
  "CAPE VERDE": "Cabo Verde",
  "SAUDI ARABIA": "Arábia Saudita",
  URUGUAY: "Uruguai",
  FRANCE: "França",
  SENEGAL: "Senegal",
  IRAQ: "Iraque",
  NORWAY: "Noruega",
  ARGENTINA: "Argentina",
  ALGERIA: "Argélia",
  AUSTRIA: "Áustria",
  JORDAN: "Jordânia",
  PORTUGAL: "Portugal",
  "DR CONGO": "RD Congo",
  UZBEKISTAN: "Uzbequistão",
  COLOMBIA: "Colômbia",
  ENGLAND: "Inglaterra",
  CROATIA: "Croácia",
  GHANA: "Gana",
  PANAMA: "Panamá",
};

export function traduzirSelecao(selecao: string): string {
  const chave = selecao.trim().toUpperCase();
  return TRADUCAO_SELECOES[chave] ?? chave;
}

export const TOOLTIPS_METRICAS: Record<string, string> = {
  GM: "Gols marcados por 90 minutos",
  GS: "Gols sofridos por 90 minutos",
  "POS%": "Posse de bola por 90 minutos",
  SG: "Jogos sem sofrer gol",
  xG: "Gols esperados (Expected goals) por 90 minutos",
  xGA: "Gols esperados contra (Expected goals against) por 90 minutos",
  FD: "Finalizações defendidas por 90 minutos",
  GCC: "Grandes chances criadas",
  TAA: "Toques na área adversária por 90 minutos",
  DS: "Desarmes por 90 minutos",
  RTF: "Recuperações de bola no terço final por 90 minutos",
  DE: "Defesas por 90 minutos",
  FS: "Faltas sofridas por 90 minutos",
  CA: "Cartões amarelos por 90 minutos",
  CV: "Cartões vermelhos por 90 minutos",
};

export const COMPETICOES_FILTRO = ["Copa 2026"] as const;
